baseURL = "https://usmanmuhd.com/"
languageCode = "en-us"
title = "Muhammad Usman"

publishDir = "docs"

theme = "cactus"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4

[params]
    description = "I am currently a Software Engineer at Cisco."
    mainSection = "posts"
    mainSectionTitle = "Recent Posts"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 6

[[params.social]]
    name = "github"
    link = "https://github.com/usmanmuhd"

[[params.social]]
    name = "email"
    link = "me@usmanmuhd.com"
