baseURL = "https://usmanmuhd.com/"
languageCode = "en-us"
title = "Muhammad Usman"

publishDir = "docs"

theme = "cactus"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4

[params]
    colortheme = "dark" # dark, light, white, or classic
    description = "I am currently a Software Engineer at Cisco."
    mainSection = "posts"
    mainSectionTitle = "Posts"
    showAllPostsOnHomePage = true
    contact = "For any queries, help or feedback, please drop a mail at [`me@usmanmuhd.com`](mailto:me@usmanmuhd.com)."

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 4

[[params.social]]
    name = "github"
    link = "https://github.com/usmanmuhd"
